# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Plugin metadata describing the plugin and its compatibility.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


@dataclass
class PluginMetadata:
    name: str
    version: str
    authors: List[str]
    description: str
    dependencies: List[str]

