# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Provides common types and utilities used across the entire plugin API.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Hand(Enum):
    """
    Represents the hands of a player.
    """
    LEFT = 0
    RIGHT = 1

class GameMode(Enum):
    """
    Represents the game modes available in Minecraft.
    """
    SURVIVAL = 0
    CREATIVE = 1
    ADVENTURE = 2
    SPECTATOR = 3

class NamedColor(Enum):
    """
    The 16 base Minecraft colors.
    """
    BLACK = 0
    DARK_BLUE = 1
    DARK_GREEN = 2
    DARK_AQUA = 3
    DARK_RED = 4
    DARK_PURPLE = 5
    GOLD = 6
    GRAY = 7
    DARK_GRAY = 8
    BLUE = 9
    GREEN = 10
    AQUA = 11
    RED = 12
    LIGHT_PURPLE = 13
    YELLOW = 14
    WHITE = 15

@dataclass
class RgbColor:
    """
    An RGB color represented by its red, green, and blue components.
    """
    r: int
    g: int
    b: int

@dataclass
class ArgbColor:
    """
    An ARGB color with alpha (transparency) channel.
    """
    a: int
    r: int
    g: int
    b: int

@dataclass
class ItemStack:
    """
    Represents a stack of items with its type and count.
    """
    registry_key: str
    count: int

class Locale(Enum):
    """
    All Minecraft-supported locales.
    """
    AF_ZA = 0
    AR_SA = 1
    AST_ES = 2
    AZ_AZ = 3
    BA_RU = 4
    BAR = 5
    BE_BY = 6
    BG_BG = 7
    BR_FR = 8
    BRB = 9
    BS_BA = 10
    CA_ES = 11
    CS_CZ = 12
    CY_GB = 13
    DA_DK = 14
    DE_AT = 15
    DE_CH = 16
    DE_DE = 17
    EL_GR = 18
    EN_AU = 19
    EN_CA = 20
    EN_GB = 21
    EN_NZ = 22
    EN_PT = 23
    EN_UD = 24
    EN_US = 25
    ENP = 26
    ENWS = 27
    EO_UY = 28
    ES_AR = 29
    ES_CL = 30
    ES_EC = 31
    ES_ES = 32
    ES_MX = 33
    ES_UY = 34
    ES_VE = 35
    ESAN = 36
    ET_EE = 37
    EU_ES = 38
    FA_IR = 39
    FI_FI = 40
    FIL_PH = 41
    FO_FO = 42
    FR_CA = 43
    FR_FR = 44
    FRA_DE = 45
    FUR_IT = 46
    FY_NL = 47
    GA_IE = 48
    GD_GB = 49
    GL_ES = 50
    HAW_US = 51
    HE_IL = 52
    HI_IN = 53
    HR_HR = 54
    HU_HU = 55
    HY_AM = 56
    ID_ID = 57
    IG_NG = 58
    IO_EN = 59
    IS_IS = 60
    ISV = 61
    IT_IT = 62
    JA_JP = 63
    JBO_EN = 64
    KA_GE = 65
    KK_KZ = 66
    KN_IN = 67
    KO_KR = 68
    KSH = 69
    KW_GB = 70
    LA_LA = 71
    LB_LU = 72
    LI_LI = 73
    LMO = 74
    LO_LA = 75
    LOL_US = 76
    LT_LT = 77
    LV_LV = 78
    LZH = 79
    MK_MK = 80
    MN_MN = 81
    MS_MY = 82
    MT_MT = 83
    NAH = 84
    NDS_DE = 85
    NL_BE = 86
    NL_NL = 87
    NN_NO = 88
    NO_NO = 89
    OC_FR = 90
    OVD = 91
    PL_PL = 92
    PT_BR = 93
    PT_PT = 94
    QYA_AA = 95
    RO_RO = 96
    RPR = 97
    RU_RU = 98
    RY_UA = 99
    SAH_SAH = 100
    SE_NO = 101
    SK_SK = 102
    SL_SI = 103
    SO_SO = 104
    SQ_AL = 105
    SR_CS = 106
    SR_SP = 107
    SV_SE = 108
    SXU = 109
    SZL = 110
    TA_IN = 111
    TH_TH = 112
    TL_PH = 113
    TLH_AA = 114
    TOK = 115
    TR_TR = 116
    TT_RU = 117
    UK_UA = 118
    VAL_ES = 119
    VEC_IT = 120
    VI_VN = 121
    YI_DE = 122
    YO_NG = 123
    ZH_CN = 124
    ZH_HK = 125
    ZH_TW = 126
    ZLM_ARAB = 127


