# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
The core context provided to a plugin during initialization and event handling.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import permission
from ..imports import event
from ..imports import server
from ..imports import command

class Context:
    """
    A contextual handle for plugin-related operations.
    """
    
    def register_event(self, handler_id: int, event_type: event.EventType, event_priority: event.EventPriority, blocking: bool) -> None:
        """
        Registers a handler for a specific event.
        
        * `handler-id`: Unique ID for the event handler.
        * `event-type`: The type of event to listen for.
        * `event-priority`: When this handler should be called relative to others.
        * `blocking`: Whether the event should wait for this handler to finish.
        """
        raise NotImplementedError
    def register_command(self, command: command.Command, permission: str) -> None:
        """
        Registers a new command.
        
        * `command`: The command definition.
        * `permission`: The required permission node to execute this command.
        """
        raise NotImplementedError
    def register_permission(self, permission: permission.Permission) -> None:
        """
        Registers a permission node with the server.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError
    def get_data_folder(self) -> str:
        """
        Returns the path to the plugin's private data folder.
        """
        raise NotImplementedError
    def get_server(self) -> server.Server:
        """
        Returns the global server instance.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



