# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import text
from ..imports import world
from ..imports import player

class EventPriority(Enum):
    HIGHEST = 0
    HIGH = 1
    NORMAL = 2
    LOW = 3
    LOWEST = 4

@dataclass
class PlayerJoinEventData:
    player: player.Player
    join_message: text.TextComponent
    cancelled: bool

@dataclass
class PlayerLeaveEventData:
    player: player.Player
    leave_message: text.TextComponent
    cancelled: bool

@dataclass
class PlayerLoginEventData:
    player: player.Player
    kick_message: text.TextComponent
    cancelled: bool

@dataclass
class PlayerChatEventData:
    player: player.Player
    message: str
    recipients: List[player.Player]
    cancelled: bool

@dataclass
class PlayerCommandSendEventData:
    player: player.Player
    command: str
    cancelled: bool

@dataclass
class PlayerPermissionCheckEventData:
    player: player.Player
    permission: str
    permission_result: bool

@dataclass
class PlayerMoveEventData:
    player: player.Player
    from_position: Tuple[float, float, float]
    to_position: Tuple[float, float, float]
    cancelled: bool

@dataclass
class PlayerTeleportEventData:
    player: player.Player
    from_position: Tuple[float, float, float]
    to_position: Tuple[float, float, float]
    cancelled: bool

@dataclass
class PlayerChangeWorldEventData:
    player: player.Player
    previous_world: world.World
    new_world: world.World
    position: Tuple[float, float, float]
    yaw: float
    pitch: float
    cancelled: bool

@dataclass
class PlayerExpChangeEventData:
    player: player.Player
    amount: int

@dataclass
class PlayerItemHeldEventData:
    player: player.Player
    previous_slot: int
    new_slot: int
    cancelled: bool

@dataclass
class PlayerChangedMainHandEventData:
    player: player.Player
    main_hand: common.Hand

@dataclass
class PlayerGamemodeChangeEventData:
    player: player.Player
    previous_gamemode: common.GameMode
    new_gamemode: common.GameMode
    cancelled: bool

@dataclass
class PlayerCustomPayloadEventData:
    player: player.Player
    channel: str
    data: bytes

class PlayerFishState(Enum):
    FISHING = 0
    CAUGHT_FISH = 1
    CAUGHT_ENTITY = 2
    IN_GROUND = 3
    FAILED_ATTEMPT = 4
    REEL_IN = 5
    BITE = 6

@dataclass
class PlayerFishEventData:
    player: player.Player
    caught_uuid: Optional[str]
    caught_type: str
    hook_uuid: str
    state: PlayerFishState
    hand: common.Hand
    exp_to_drop: int
    cancelled: bool

@dataclass
class PlayerEggThrowEventData:
    player: player.Player
    egg_uuid: str
    hatching: bool
    num_hatches: int
    hatching_type: str
    cancelled: bool

class EntityInteractionAction(Enum):
    INTERACT = 0
    ATTACK = 1
    INTERACT_AT = 2

class InteractAction(Enum):
    LEFT_CLICK_BLOCK = 0
    LEFT_CLICK_AIR = 1
    RIGHT_CLICK_AIR = 2
    RIGHT_CLICK_BLOCK = 3

@dataclass
class PlayerInteractEventData:
    player: player.Player
    action: InteractAction
    clicked_pos: Optional[Tuple[int, int, int]]
    item: common.ItemStack
    block: str
    cancelled: bool

@dataclass
class PlayerToggleSneakEventData:
    player: player.Player
    is_sneaking: bool
    cancelled: bool

@dataclass
class PlayerToggleSprintEventData:
    player: player.Player
    is_sprinting: bool
    cancelled: bool

@dataclass
class PlayerInteractUnknownEntityEventData:
    player: player.Player
    entity_id: int
    action: EntityInteractionAction
    cancelled: bool

@dataclass
class BlockRedstoneEventData:
    target_world: world.World
    state_id: int
    block_position: Tuple[int, int, int]
    old_current: int
    new_current: int
    cancelled: bool

@dataclass
class BlockBreakEventData:
    player: Optional[player.Player]
    block: str
    block_position: Tuple[int, int, int]
    exp: int
    should_drop: bool
    cancelled: bool

@dataclass
class BlockBurnEventData:
    igniting_block: str
    block: str
    cancelled: bool

@dataclass
class BlockCanBuildEventData:
    block_to_build: str
    buildable: bool
    player: player.Player
    block: str
    cancelled: bool

@dataclass
class BlockGrowEventData:
    target_world: world.World
    old_block: str
    old_state_id: int
    new_block: str
    new_state_id: int
    block_position: Tuple[int, int, int]
    cancelled: bool

@dataclass
class BlockPlaceEventData:
    player: player.Player
    block_placed: str
    block_placed_against: str
    block_position: Tuple[int, int, int]
    can_build: bool
    cancelled: bool

@dataclass
class ServerCommandEventData:
    command: str
    cancelled: bool

@dataclass
class SpawnChangeEventData:
    target_world: world.World
    previous_position: Tuple[int, int, int]
    previous_yaw: float
    previous_pitch: float
    new_position: Tuple[int, int, int]
    new_yaw: float
    new_pitch: float

@dataclass
class ServerBroadcastEventData:
    message: text.TextComponent
    sender: text.TextComponent
    cancelled: bool

class EventType(Enum):
    PLAYER_JOIN_EVENT = 0
    PLAYER_LEAVE_EVENT = 1
    PLAYER_LOGIN_EVENT = 2
    PLAYER_CHAT_EVENT = 3
    PLAYER_COMMAND_SEND_EVENT = 4
    PLAYER_PERMISSION_CHECK_EVENT = 5
    PLAYER_MOVE_EVENT = 6
    PLAYER_TELEPORT_EVENT = 7
    PLAYER_CHANGE_WORLD_EVENT = 8
    PLAYER_EXP_CHANGE_EVENT = 9
    PLAYER_ITEM_HELD_EVENT = 10
    PLAYER_CHANGED_MAIN_HAND_EVENT = 11
    PLAYER_GAMEMODE_CHANGE_EVENT = 12
    PLAYER_CUSTOM_PAYLOAD_EVENT = 13
    PLAYER_FISH_EVENT = 14
    PLAYER_EGG_THROW_EVENT = 15
    PLAYER_INTERACT_UNKNOWN_ENTITY_EVENT = 16
    PLAYER_INTERACT_EVENT = 17
    PLAYER_TOGGLE_SNEAK_EVENT = 18
    PLAYER_TOGGLE_SPRINT_EVENT = 19
    BLOCK_REDSTONE_EVENT = 20
    BLOCK_BREAK_EVENT = 21
    BLOCK_BURN_EVENT = 22
    BLOCK_CAN_BUILD_EVENT = 23
    BLOCK_GROW_EVENT = 24
    BLOCK_PLACE_EVENT = 25
    SERVER_COMMAND_EVENT = 26
    SPAWN_CHANGE_EVENT = 27
    SERVER_BROADCAST_EVENT = 28


@dataclass
class Event_PlayerJoinEvent:
    value: PlayerJoinEventData


@dataclass
class Event_PlayerLeaveEvent:
    value: PlayerLeaveEventData


@dataclass
class Event_PlayerLoginEvent:
    value: PlayerLoginEventData


@dataclass
class Event_PlayerChatEvent:
    value: PlayerChatEventData


@dataclass
class Event_PlayerCommandSendEvent:
    value: PlayerCommandSendEventData


@dataclass
class Event_PlayerPermissionCheckEvent:
    value: PlayerPermissionCheckEventData


@dataclass
class Event_PlayerMoveEvent:
    value: PlayerMoveEventData


@dataclass
class Event_PlayerTeleportEvent:
    value: PlayerTeleportEventData


@dataclass
class Event_PlayerChangeWorldEvent:
    value: PlayerChangeWorldEventData


@dataclass
class Event_PlayerExpChangeEvent:
    value: PlayerExpChangeEventData


@dataclass
class Event_PlayerItemHeldEvent:
    value: PlayerItemHeldEventData


@dataclass
class Event_PlayerChangedMainHandEvent:
    value: PlayerChangedMainHandEventData


@dataclass
class Event_PlayerGamemodeChangeEvent:
    value: PlayerGamemodeChangeEventData


@dataclass
class Event_PlayerCustomPayloadEvent:
    value: PlayerCustomPayloadEventData


@dataclass
class Event_PlayerFishEvent:
    value: PlayerFishEventData


@dataclass
class Event_PlayerEggThrowEvent:
    value: PlayerEggThrowEventData


@dataclass
class Event_PlayerInteractUnknownEntityEvent:
    value: PlayerInteractUnknownEntityEventData


@dataclass
class Event_PlayerInteractEvent:
    value: PlayerInteractEventData


@dataclass
class Event_PlayerToggleSneakEvent:
    value: PlayerToggleSneakEventData


@dataclass
class Event_PlayerToggleSprintEvent:
    value: PlayerToggleSprintEventData


@dataclass
class Event_BlockRedstoneEvent:
    value: BlockRedstoneEventData


@dataclass
class Event_BlockBreakEvent:
    value: BlockBreakEventData


@dataclass
class Event_BlockBurnEvent:
    value: BlockBurnEventData


@dataclass
class Event_BlockCanBuildEvent:
    value: BlockCanBuildEventData


@dataclass
class Event_BlockGrowEvent:
    value: BlockGrowEventData


@dataclass
class Event_BlockPlaceEvent:
    value: BlockPlaceEventData


@dataclass
class Event_ServerCommandEvent:
    value: ServerCommandEventData


@dataclass
class Event_SpawnChangeEvent:
    value: SpawnChangeEventData


@dataclass
class Event_ServerBroadcastEvent:
    value: ServerBroadcastEventData


Event = Union[Event_PlayerJoinEvent, Event_PlayerLeaveEvent, Event_PlayerLoginEvent, Event_PlayerChatEvent, Event_PlayerCommandSendEvent, Event_PlayerPermissionCheckEvent, Event_PlayerMoveEvent, Event_PlayerTeleportEvent, Event_PlayerChangeWorldEvent, Event_PlayerExpChangeEvent, Event_PlayerItemHeldEvent, Event_PlayerChangedMainHandEvent, Event_PlayerGamemodeChangeEvent, Event_PlayerCustomPayloadEvent, Event_PlayerFishEvent, Event_PlayerEggThrowEvent, Event_PlayerInteractUnknownEntityEvent, Event_PlayerInteractEvent, Event_PlayerToggleSneakEvent, Event_PlayerToggleSprintEvent, Event_BlockRedstoneEvent, Event_BlockBreakEvent, Event_BlockBurnEvent, Event_BlockCanBuildEvent, Event_BlockGrowEvent, Event_BlockPlaceEvent, Event_ServerCommandEvent, Event_SpawnChangeEvent, Event_ServerBroadcastEvent]



