# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class Level(Enum):
    TRACE = 0
    DEBUG = 1
    INFO = 2
    WARN = 3
    ERROR = 4


def log(level: Level, message: str) -> None:
    """
    log any general purpose message
    """
    raise NotImplementedError
def log_tracing(event: bytes) -> None:
    """
    This function is meant to be used by the tracing crate.
    """
    raise NotImplementedError
