# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import player

class Difficulty(Enum):
    """
    Represents the difficulty setting of a Minecraft server.
    """
    PEACEFUL = 0
    EASY = 1
    NORMAL = 2
    HARD = 3

class Server:
    """
    Represents the global server instance.
    """
    
    def get_difficulty(self) -> Difficulty:
        """
        Returns the current difficulty level of the server.
        """
        raise NotImplementedError
    def get_player_count(self) -> int:
        """
        Returns the total number of players currently connected to the server.
        """
        raise NotImplementedError
    def get_mspt(self) -> float:
        """
        Returns the rolling average Milliseconds Per Tick (MSPT).
        A value below 50.0 is required for a stable 20 TPS.
        """
        raise NotImplementedError
    def get_tps(self) -> float:
        """
        Returns the effective Ticks Per Second (TPS).
        Ideal value is 20.0.
        """
        raise NotImplementedError
    def get_all_players(self) -> List[player.Player]:
        """
        Returns a list of all online players across all worlds.
        """
        raise NotImplementedError
    def get_player_by_name(self, name: str) -> Optional[player.Player]:
        """
        Searches for a player by their exact name.
        """
        raise NotImplementedError
    def get_player_by_uuid(self, id: str) -> Optional[player.Player]:
        """
        Searches for a player by their UUID string.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



