# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common

class TextComponent:
    
    @classmethod
    def text(cls, plain: str) -> Self:
        raise NotImplementedError
    @classmethod
    def translate(cls, key: str, with_: List[Self]) -> Self:
        raise NotImplementedError
    def add_child(self, child: Self) -> None:
        raise NotImplementedError
    def add_text(self, text: str) -> None:
        raise NotImplementedError
    def get_text(self) -> str:
        raise NotImplementedError
    def encode(self) -> bytes:
        raise NotImplementedError
    def color_named(self, color: common.NamedColor) -> None:
        """
        Style
        """
        raise NotImplementedError
    def color_rgb(self, color: common.RgbColor) -> None:
        raise NotImplementedError
    def bold(self, value: bool) -> None:
        raise NotImplementedError
    def italic(self, value: bool) -> None:
        raise NotImplementedError
    def underlined(self, value: bool) -> None:
        raise NotImplementedError
    def strikethrough(self, value: bool) -> None:
        raise NotImplementedError
    def obfuscated(self, value: bool) -> None:
        raise NotImplementedError
    def insertion(self, text: str) -> None:
        """
        Text inserted into chat when shift-clicked
        """
        raise NotImplementedError
    def font(self, font: str) -> None:
        raise NotImplementedError
    def shadow_color(self, color: common.ArgbColor) -> None:
        raise NotImplementedError
    def click_open_url(self, url: str) -> None:
        """
        Click events
        """
        raise NotImplementedError
    def click_run_command(self, command: str) -> None:
        raise NotImplementedError
    def click_suggest_command(self, command: str) -> None:
        raise NotImplementedError
    def click_copy_to_clipboard(self, text: str) -> None:
        raise NotImplementedError
    def hover_show_text(self, text: Self) -> None:
        """
        Hover events
        """
        raise NotImplementedError
    def hover_show_item(self, item: str) -> None:
        """
        Item data as SNBT string
        """
        raise NotImplementedError
    def hover_show_entity(self, entity_type: str, id: str, name: Optional[Self]) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



