# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from .imports import event
from .imports import server
from .imports import command
from .imports import context


class WitWorld(Protocol):

    @abstractmethod
    def init_plugin(self) -> None:
        """
        --- Plugin-provided exports ---
        Called by the host once to initialize the plugin.
        Internal use only; plugins should use the `register_plugin!` macro.
        """
        raise NotImplementedError

    @abstractmethod
    def on_load(self, context: context.Context) -> None:
        """
        Called when the plugin is being loaded.
        Use this to register commands, events, and perform initial setup.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError

    @abstractmethod
    def on_unload(self, context: context.Context) -> None:
        """
        Called when the plugin is being unloaded.
        Use this to save data and clean up resources.
        
        Raises: `componentize_py_types.Err(wit_world.imports.str)`
        """
        raise NotImplementedError

    @abstractmethod
    def handle_event(self, event_id: int, server: server.Server, event: event.Event) -> event.Event:
        """
        Dispatches an event to the plugin for handling.
        """
        raise NotImplementedError

    @abstractmethod
    def handle_command(self, command_id: int, sender: command.CommandSender, server: server.Server, args: command.ConsumedArgs) -> int:
        """
        Dispatches a command execution to the plugin.
        
        Raises: `componentize_py_types.Err(wit_world.imports.command.CommandError)`
        """
        raise NotImplementedError

    @abstractmethod
    def handle_task(self, handler_id: int, server: server.Server) -> None:
        """
        Dispatches a scheduled task execution to the plugin.
        """
        raise NotImplementedError

