# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class BlockEntity:
    
    def resource_location(self) -> str:
        raise NotImplementedError
    def get_position(self) -> Tuple[int, int, int]:
        raise NotImplementedError
    def get_id(self) -> int:
        raise NotImplementedError
    def is_dirty(self) -> bool:
        """
        write-nbt: func(nbt: nbt-compound);
        from-nbt: func(nbt: nbt-compound, position: block-position) -> entity;
        tick: func(world: simple-world);
        write-internal: func(nbt: nbt-compound);
        chunk-data-nbt: func() -> option<nbt-compound;
        get-inventory: func() -> option<inventory>;
        set-block-state: func(block-state: block-state-id);
        on-block-replaced: func(world: simple-world, position: block-position);
        """
        raise NotImplementedError
    def clear_dirty(self) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class CommandBlockEntity:
    
    def get_block_entity(self) -> BlockEntity:
        raise NotImplementedError
    def last_output(self) -> str:
        raise NotImplementedError
    def track_output(self) -> bool:
        raise NotImplementedError
    def success_count(self) -> int:
        raise NotImplementedError
    def command(self) -> str:
        raise NotImplementedError
    def auto(self) -> bool:
        raise NotImplementedError
    def condition_met(self) -> bool:
        raise NotImplementedError
    def powered(self) -> bool:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



@dataclass
class BlockEntityType_CommandBlockEntity:
    value: CommandBlockEntity


BlockEntityType = Union[BlockEntityType_CommandBlockEntity]



