# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import block_entity
from ..imports import text
from ..imports import world
from ..imports import player
from ..imports import server

class Gamemode(Enum):
    SURVIVAL = 0
    CREATIVE = 1
    ADVENTURE = 2
    SPECTATOR = 3

class BossbarColor(Enum):
    PINK = 0
    BLUE = 1
    RED = 2
    GREEN = 3
    YELLOW = 4
    PURPLE = 5
    WHITE = 6

class BossbarStyle(Enum):
    NO_DIVISION = 0
    NOTCHES6 = 1
    NOTCHES10 = 2
    NOTCHES12 = 3
    NOTCHES20 = 4

class SoundCategory(Enum):
    MASTER = 0
    MUSIC = 1
    RECORDS = 2
    WEATHER = 3
    BLOCKS = 4
    HOSTILE = 5
    NEUTRAL = 6
    PLAYERS = 7
    AMBIENT = 8
    VOICE = 9
    UI = 10

class EntityAnchor(Enum):
    FEET = 0
    EYES = 1


@dataclass
class Number_Float64:
    value: float


@dataclass
class Number_Float32:
    value: float


@dataclass
class Number_Int32:
    value: int


@dataclass
class Number_Int64:
    value: int


Number = Union[Number_Float64, Number_Float32, Number_Int32, Number_Int64]



@dataclass
class NotInBounds_LowerBound:
    value: Tuple[Number, Number]


@dataclass
class NotInBounds_UpperBound:
    value: Tuple[Number, Number]


NotInBounds = Union[NotInBounds_LowerBound, NotInBounds_UpperBound]



@dataclass
class Arg_Entities:
    value: List[world.Entity]


@dataclass
class Arg_Entity:
    value: world.Entity


@dataclass
class Arg_Players:
    value: List[player.Player]


@dataclass
class Arg_BlockPos:
    value: Tuple[int, int, int]


@dataclass
class Arg_Pos3d:
    value: Tuple[float, float, float]


@dataclass
class Arg_Pos2d:
    value: Tuple[float, float]


@dataclass
class Arg_Rotation:
    value: Tuple[float, bool, float, bool]


@dataclass
class Arg_GameMode:
    value: Gamemode


@dataclass
class Arg_Difficulty:
    value: server.Difficulty


@dataclass
class Arg_Item:
    value: str


@dataclass
class Arg_ItemPredicate:
    value: str


@dataclass
class Arg_ResourceLocation:
    value: str


@dataclass
class Arg_Block:
    value: str


@dataclass
class Arg_BlockPredicate:
    value: str


@dataclass
class Arg_BossbarColor:
    value: BossbarColor


@dataclass
class Arg_BossbarStyle:
    value: BossbarStyle


@dataclass
class Arg_Particle:
    value: str


@dataclass
class Arg_Msg:
    value: str


@dataclass
class Arg_TextComponent:
    value: text.TextComponent


@dataclass
class Arg_Time:
    value: int


@dataclass
class Arg_Num:
    value: Result[Number, NotInBounds]


@dataclass
class Arg_Bool:
    value: bool


@dataclass
class Arg_Simple:
    value: str


@dataclass
class Arg_SoundCategory:
    value: SoundCategory


@dataclass
class Arg_DamageType:
    value: str


@dataclass
class Arg_Effect:
    value: str


@dataclass
class Arg_Enchantment:
    value: str


@dataclass
class Arg_EntityAnchor:
    value: EntityAnchor


Arg = Union[Arg_Entities, Arg_Entity, Arg_Players, Arg_BlockPos, Arg_Pos3d, Arg_Pos2d, Arg_Rotation, Arg_GameMode, Arg_Difficulty, Arg_Item, Arg_ItemPredicate, Arg_ResourceLocation, Arg_Block, Arg_BlockPredicate, Arg_BossbarColor, Arg_BossbarStyle, Arg_Particle, Arg_Msg, Arg_TextComponent, Arg_Time, Arg_Num, Arg_Bool, Arg_Simple, Arg_SoundCategory, Arg_DamageType, Arg_Effect, Arg_Enchantment, Arg_EntityAnchor]


class ConsumedArgs:
    
    def get_value(self, key: str) -> Arg:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



@dataclass
class CommandSenderType_Rcon:
    pass


@dataclass
class CommandSenderType_Console:
    pass


@dataclass
class CommandSenderType_Player:
    value: player.Player


@dataclass
class CommandSenderType_CommandBlock:
    value: Tuple[block_entity.CommandBlockEntity, world.World]


@dataclass
class CommandSenderType_Dummy:
    pass


CommandSenderType = Union[CommandSenderType_Rcon, CommandSenderType_Console, CommandSenderType_Player, CommandSenderType_CommandBlock, CommandSenderType_Dummy]


class PermissionLevel(Enum):
    ZERO = 0
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4

class CommandSender:
    
    def get_command_sender_type(self) -> CommandSenderType:
        raise NotImplementedError
    def send_message(self, text: text.TextComponent) -> None:
        raise NotImplementedError
    def set_success_count(self, count: int) -> None:
        raise NotImplementedError
    def is_player(self) -> bool:
        raise NotImplementedError
    def is_console(self) -> bool:
        raise NotImplementedError
    def as_player(self) -> Optional[player.Player]:
        raise NotImplementedError
    def permission_level(self) -> PermissionLevel:
        raise NotImplementedError
    def has_permission_level(self, level: PermissionLevel) -> bool:
        raise NotImplementedError
    def has_permission(self, server: server.Server, node: str) -> bool:
        raise NotImplementedError
    def position(self) -> Optional[Tuple[float, float, float]]:
        raise NotImplementedError
    def world(self) -> Optional[world.World]:
        raise NotImplementedError
    def get_locale(self) -> common.Locale:
        raise NotImplementedError
    def should_receive_feedback(self) -> bool:
        raise NotImplementedError
    def should_broadcast_console_to_ops(self) -> bool:
        raise NotImplementedError
    def should_track_output(self) -> bool:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class StringType(Enum):
    SINGLE_WORD = 0
    QUOTABLE = 1
    GREEDY = 2


@dataclass
class ArgumentType_Bool:
    pass


@dataclass
class ArgumentType_Float:
    value: Tuple[Optional[float], Optional[float]]


@dataclass
class ArgumentType_Double:
    value: Tuple[Optional[float], Optional[float]]


@dataclass
class ArgumentType_Integer:
    value: Tuple[Optional[int], Optional[int]]


@dataclass
class ArgumentType_Long:
    value: Tuple[Optional[int], Optional[int]]


@dataclass
class ArgumentType_String:
    value: StringType


@dataclass
class ArgumentType_Entities:
    pass


@dataclass
class ArgumentType_Entity:
    pass


@dataclass
class ArgumentType_Players:
    pass


@dataclass
class ArgumentType_GameProfile:
    pass


@dataclass
class ArgumentType_BlockPos:
    pass


@dataclass
class ArgumentType_Position3d:
    pass


@dataclass
class ArgumentType_Position2d:
    pass


@dataclass
class ArgumentType_BlockState:
    pass


@dataclass
class ArgumentType_BlockPredicate:
    pass


@dataclass
class ArgumentType_Item:
    pass


@dataclass
class ArgumentType_ItemPredicate:
    pass


@dataclass
class ArgumentType_Component:
    pass


@dataclass
class ArgumentType_Rotation:
    pass


@dataclass
class ArgumentType_ResourceLocation:
    pass


@dataclass
class ArgumentType_EntityAnchor:
    pass


@dataclass
class ArgumentType_Gamemode:
    pass


@dataclass
class ArgumentType_Difficulty:
    pass


@dataclass
class ArgumentType_Time:
    value: int


@dataclass
class ArgumentType_Resource:
    value: str


ArgumentType = Union[ArgumentType_Bool, ArgumentType_Float, ArgumentType_Double, ArgumentType_Integer, ArgumentType_Long, ArgumentType_String, ArgumentType_Entities, ArgumentType_Entity, ArgumentType_Players, ArgumentType_GameProfile, ArgumentType_BlockPos, ArgumentType_Position3d, ArgumentType_Position2d, ArgumentType_BlockState, ArgumentType_BlockPredicate, ArgumentType_Item, ArgumentType_ItemPredicate, ArgumentType_Component, ArgumentType_Rotation, ArgumentType_ResourceLocation, ArgumentType_EntityAnchor, ArgumentType_Gamemode, ArgumentType_Difficulty, ArgumentType_Time, ArgumentType_Resource]



@dataclass
class CommandError_InvalidConsumption:
    value: Optional[str]


@dataclass
class CommandError_InvalidRequirement:
    pass


@dataclass
class CommandError_PermissionDenied:
    pass


@dataclass
class CommandError_CommandFailed:
    value: text.TextComponent


CommandError = Union[CommandError_InvalidConsumption, CommandError_InvalidRequirement, CommandError_PermissionDenied, CommandError_CommandFailed]


class CommandNode:
    
    @classmethod
    def literal(cls, name: str) -> Self:
        raise NotImplementedError
    @classmethod
    def argument(cls, name: str, arg_type: ArgumentType) -> Self:
        raise NotImplementedError
    def then(self, node: Self) -> None:
        raise NotImplementedError
    def execute_with_handler_id(self, handler_id: int) -> None:
        raise NotImplementedError
    def require_with_handler_id(self, handler_id: int) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Command:
    
    def __init__(self, names: List[str], description: str) -> None:
        """
        First name is primary, rest are aliases
        """
        raise NotImplementedError

    def then(self, node: CommandNode) -> None:
        raise NotImplementedError
    def execute_with_handler_id(self, handler_id: int) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



