# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import text

class GuiType(Enum):
    GENERIC_9X1 = 0
    GENERIC_9X2 = 1
    GENERIC_9X3 = 2
    GENERIC_9X4 = 3
    GENERIC_9X5 = 4
    GENERIC_9X6 = 5
    GENERIC_3X3 = 6
    CRAFTER_3X3 = 7
    ANVIL = 8
    BEACON = 9
    BLAST_FURNACE = 10
    BREWING_STAND = 11
    CRAFTING = 12
    ENCHANTMENT = 13
    FURNACE = 14
    GRINDSTONE = 15
    HOPPER = 16
    LECTERN = 17
    LOOM = 18
    MERCHANT = 19
    SHULKER_BOX = 20
    SMITHING = 21
    SMOKER = 22
    CARTOGRAPHY_TABLE = 23
    STONECUTTER = 24

class Gui:
    
    def __init__(self, type: GuiType, title: text.TextComponent) -> None:
        raise NotImplementedError

    def set_item(self, slot: int, item: common.ItemStack) -> None:
        raise NotImplementedError
    def get_item(self, slot: int) -> Optional[common.ItemStack]:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



