# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common


def translate(key: str, locale: common.Locale) -> str:
    """
    Retrieves a translated string from the host.
    
    # Arguments
    * `key`: The namespaced translation key (e.g. `pumpkin:my_key`).
    * `locale`: The target locale.
    
    # Returns
    The localized string, falling back to English or the key itself.
    """
    raise NotImplementedError
def load_translations(namespace: str, json: str, locale: common.Locale) -> None:
    """
    Loads custom translations from a JSON string.
    
    # Arguments
    * `namespace`: The namespace to associate these keys with.
    * `json`: A JSON string containing a flat map of translations.
    * `locale`: The target locale for these translations.
    """
    raise NotImplementedError
