# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some


class PermissionLevel(Enum):
    """
    Represents the player's permission level
    
    Permission levels determine the player's access to commands and server operations.
    Each numeric level corresponds to a specific role:
    - `Zero`: `normal`: Player can use basic commands.
    - `One`: `moderator`: Player can bypass spawn protection.
    - `Two`: `gamemaster`: Player or executor can use more commands and player can use command blocks.
    - `Three`:  `admin`: Player or executor can use commands related to multiplayer management.
    - `Four`: `owner`: Player or executor can use all of the commands, including commands related to server management.
    """
    ZERO = 0
    ONE = 1
    TWO = 2
    THREE = 3
    FOUR = 4


@dataclass
class PermissionDefault_Deny:
    pass


@dataclass
class PermissionDefault_Allow:
    pass


@dataclass
class PermissionDefault_Op:
    value: PermissionLevel


PermissionDefault = Union[PermissionDefault_Deny, PermissionDefault_Allow, PermissionDefault_Op]
"""
Describes the default behavior for permissions
"""


@dataclass
class PermissionChild:
    """
    A child permission entry
    """
    node: str
    value: bool

@dataclass
class Permission:
    """
    Defines a permission node in the system
    """
    node: str
    description: str
    default: PermissionDefault
    children: List[PermissionChild]


