# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Represents a player connected to the Minecraft server.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import permission
from ..imports import text
from ..imports import gui
from ..imports import world

@dataclass
class PlayerAbilities:
    """
    Various abilities a player can have.
    """
    invulnerable: bool
    flying: bool
    allow_flying: bool
    creative: bool
    allow_modify_world: bool
    fly_speed: float
    walk_speed: float

class Player:
    """
    A handle to a player on the server.
    """
    
    def as_entity(self) -> world.Entity:
        """
        Returns the player as an entity.
        """
        raise NotImplementedError
    def get_id(self) -> str:
        """
        Returns the player's unique UUID as a string.
        """
        raise NotImplementedError
    def get_name(self) -> str:
        """
        Returns the player's username.
        """
        raise NotImplementedError
    def get_position(self) -> Tuple[float, float, float]:
        """
        Basic state
        Returns the player's current position in the world.
        """
        raise NotImplementedError
    def get_yaw(self) -> float:
        """
        Returns the player's current yaw (horizontal rotation).
        """
        raise NotImplementedError
    def get_pitch(self) -> float:
        """
        Returns the player's current pitch (vertical rotation).
        """
        raise NotImplementedError
    def get_world(self) -> world.World:
        """
        Returns the world the player is currently in.
        """
        raise NotImplementedError
    def get_gamemode(self) -> common.GameMode:
        """
        Returns the player's current game mode.
        """
        raise NotImplementedError
    def set_gamemode(self, mode: common.GameMode) -> bool:
        """
        Changes the player's game mode. Returns true if successful.
        """
        raise NotImplementedError
    def get_locale(self) -> str:
        """
        Returns the player's locale (e.g., "en_us").
        """
        raise NotImplementedError
    def get_ping(self) -> int:
        """
        Returns the player's current ping in milliseconds.
        """
        raise NotImplementedError
    def get_permission_level(self) -> permission.PermissionLevel:
        """
        Permissions & metadata
        Returns the player's permission level (0-4).
        """
        raise NotImplementedError
    def set_permission_level(self, level: permission.PermissionLevel) -> None:
        """
        Sets the player's permission level.
        """
        raise NotImplementedError
    def has_permission(self, node: str) -> bool:
        """
        Checks if the player has a specific permission node.
        """
        raise NotImplementedError
    def get_display_name(self) -> text.TextComponent:
        """
        Returns the player's display name, which may include formatting.
        """
        raise NotImplementedError
    def send_system_message(self, text: text.TextComponent, overlay: bool) -> None:
        """
        Messaging & titles
        Sends a system message to the player's chat.
        """
        raise NotImplementedError
    def show_title(self, text: text.TextComponent) -> None:
        """
        Shows a large title on the player's screen.
        """
        raise NotImplementedError
    def show_subtitle(self, text: text.TextComponent) -> None:
        """
        Shows a smaller subtitle on the player's screen.
        """
        raise NotImplementedError
    def show_actionbar(self, text: text.TextComponent) -> None:
        """
        Shows a message in the action bar area.
        """
        raise NotImplementedError
    def send_title_animation(self, fade_in: int, stay: int, fade_out: int) -> None:
        """
        Sets the fade-in, stay, and fade-out times for titles.
        """
        raise NotImplementedError
    def teleport(self, position: Tuple[float, float, float], yaw: Optional[float], pitch: Optional[float], world: world.World) -> None:
        """
        Teleport & kick
        Teleports the player to a position in a world.
        """
        raise NotImplementedError
    def teleport_world(self, world_ref: world.World, position: Tuple[float, float, float], yaw: Optional[float], pitch: Optional[float]) -> None:
        """
        Teleports the player to another world at a specific position.
        """
        raise NotImplementedError
    def kick(self, message: text.TextComponent) -> None:
        """
        Kicks the player from the server with the specified reason.
        """
        raise NotImplementedError
    def respawn(self) -> None:
        """
        Forces the player to respawn.
        """
        raise NotImplementedError
    def open_gui(self, gui_ref: gui.Gui) -> None:
        """
        Opens a GUI for the player.
        """
        raise NotImplementedError
    def ban(self, reason: Optional[text.TextComponent]) -> None:
        """
        Bans the player with an optional reason.
        """
        raise NotImplementedError
    def ban_ip(self, reason: Optional[text.TextComponent]) -> None:
        """
        Bans the player's IP address with an optional reason.
        """
        raise NotImplementedError
    def get_selected_slot(self) -> int:
        """
        Inventory
        Returns the index of the currently selected hotbar slot (0-8).
        """
        raise NotImplementedError
    def get_item_in_hand(self, hand: common.Hand) -> Optional[common.ItemStack]:
        """
        Returns the item currently in the specified hand.
        """
        raise NotImplementedError
    def get_inventory_item(self, slot: int) -> Optional[common.ItemStack]:
        """
        Returns the item in the specified inventory slot.
        """
        raise NotImplementedError
    def get_health(self) -> float:
        """
        Status
        Returns the player's current health.
        """
        raise NotImplementedError
    def set_health(self, health: float) -> None:
        """
        Sets the player's current health.
        """
        raise NotImplementedError
    def get_max_health(self) -> float:
        """
        Returns the player's maximum health.
        """
        raise NotImplementedError
    def set_max_health(self, max_health: float) -> None:
        """
        Sets the player's maximum health.
        """
        raise NotImplementedError
    def get_food_level(self) -> int:
        """
        Returns the player's food level (0-20).
        """
        raise NotImplementedError
    def set_food_level(self, food_level: int) -> None:
        """
        Sets the player's food level.
        """
        raise NotImplementedError
    def get_saturation(self) -> float:
        """
        Returns the player's food saturation level.
        """
        raise NotImplementedError
    def set_saturation(self, saturation: float) -> None:
        """
        Sets the player's food saturation level.
        """
        raise NotImplementedError
    def get_exhaustion(self) -> float:
        """
        Returns the player's food exhaustion level.
        """
        raise NotImplementedError
    def set_exhaustion(self, exhaustion: float) -> None:
        """
        Sets the player's food exhaustion level.
        """
        raise NotImplementedError
    def get_absorption(self) -> float:
        """
        Returns the player's current absorption amount.
        """
        raise NotImplementedError
    def set_absorption(self, absorption: float) -> None:
        """
        Sets the player's current absorption amount.
        """
        raise NotImplementedError
    def get_experience_level(self) -> int:
        """
        Returns the player's total experience level.
        """
        raise NotImplementedError
    def get_experience_progress(self) -> float:
        """
        Returns the player's progress toward the next level (0.0 to 1.0).
        """
        raise NotImplementedError
    def get_experience_points(self) -> int:
        """
        Returns the total experience points the player has.
        """
        raise NotImplementedError
    def set_experience_level(self, level: int) -> None:
        """
        Sets the player's total experience level.
        """
        raise NotImplementedError
    def set_experience_progress(self, progress: float) -> None:
        """
        Sets the player's progress toward the next level.
        """
        raise NotImplementedError
    def set_experience_points(self, points: int) -> None:
        """
        Sets the player's total experience points.
        """
        raise NotImplementedError
    def add_experience_levels(self, levels: int) -> None:
        """
        Adds experience levels to the player.
        """
        raise NotImplementedError
    def add_experience_points(self, points: int) -> None:
        """
        Adds experience points to the player.
        """
        raise NotImplementedError
    def is_sneaking(self) -> bool:
        """
        Returns whether the player is currently sneaking.
        """
        raise NotImplementedError
    def set_sneaking(self, sneaking: bool) -> None:
        """
        Sets whether the player is currently sneaking.
        """
        raise NotImplementedError
    def is_sprinting(self) -> bool:
        """
        Returns whether the player is currently sprinting.
        """
        raise NotImplementedError
    def set_sprinting(self, sprinting: bool) -> None:
        """
        Sets whether the player is currently sprinting.
        """
        raise NotImplementedError
    def is_on_ground(self) -> bool:
        """
        Returns whether the player is currently on the ground.
        """
        raise NotImplementedError
    def is_flying(self) -> bool:
        """
        Returns whether the player is currently flying.
        """
        raise NotImplementedError
    def set_flying(self, flying: bool) -> None:
        """
        Sets whether the player should be flying.
        """
        raise NotImplementedError
    def get_abilities(self) -> PlayerAbilities:
        """
        Returns the player's current abilities.
        """
        raise NotImplementedError
    def set_abilities(self, abilities: PlayerAbilities) -> None:
        """
        Updates the player's abilities.
        """
        raise NotImplementedError
    def get_ip(self) -> str:
        """
        Returns the player's IP address.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



