# This file is automatically generated by componentize-py
# It is not intended for manual editing.
"""
Provides functionality to schedule tasks to be executed later on the server.
"""
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some



def schedule_delayed_task(handler_id: int, delay_ticks: int) -> int:
    """
    Schedules a task to be executed once after the specified number of ticks.
    
    * `handler-id`: The unique ID of the handler to call when the task executes.
    * `delay-ticks`: The number of game ticks to wait before execution (20 ticks = 1 second).
    
    Returns a unique task ID that can be used to cancel the task.
    """
    raise NotImplementedError
def schedule_repeating_task(handler_id: int, delay_ticks: int, period_ticks: int) -> int:
    """
    Schedules a task to be executed repeatedly.
    
    * `handler-id`: The unique ID of the handler to call when the task executes.
    * `delay-ticks`: The number of game ticks to wait before the first execution.
    * `period-ticks`: The number of game ticks between subsequent executions.
    
    Returns a unique task ID that can be used to cancel the task.
    """
    raise NotImplementedError
def cancel_task(task_id: int) -> None:
    """
    Cancels a scheduled task if it hasn't finished yet.
    
    * `task-id`: The ID of the task to cancel.
    """
    raise NotImplementedError
