# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import text

class RenderType(Enum):
    INTEGER = 0
    HEARTS = 1

class DisplaySlot(Enum):
    PLAYER_LIST = 0
    SIDEBAR = 1
    BELOW_NAME = 2
    SIDEBAR_TEAM_BLACK = 3
    SIDEBAR_TEAM_DARK_BLUE = 4
    SIDEBAR_TEAM_DARK_GREEN = 5
    SIDEBAR_TEAM_DARK_AQUA = 6
    SIDEBAR_TEAM_DARK_RED = 7
    SIDEBAR_TEAM_DARK_PURPLE = 8
    SIDEBAR_TEAM_GOLD = 9
    SIDEBAR_TEAM_GRAY = 10
    SIDEBAR_TEAM_DARK_GRAY = 11
    SIDEBAR_TEAM_BLUE = 12
    SIDEBAR_TEAM_GREEN = 13
    SIDEBAR_TEAM_AQUA = 14
    SIDEBAR_TEAM_RED = 15
    SIDEBAR_TEAM_LIGHT_PURPLE = 16
    SIDEBAR_TEAM_YELLOW = 17
    SIDEBAR_TEAM_WHITE = 18

class NametagVisibility(Enum):
    ALWAYS = 0
    NEVER = 1
    HIDE_FOR_OTHER_TEAMS = 2
    HIDE_FOR_OWN_TEAM = 3

class CollisionRule(Enum):
    ALWAYS = 0
    NEVER = 1
    PUSH_OTHER_TEAMS = 2
    PUSH_OWN_TEAM = 3

@dataclass
class TeamSettings:
    display_name: text.TextComponent
    friendly_fire: bool
    see_friendly_invisibles: bool
    nametag_visibility: NametagVisibility
    collision_rule: CollisionRule
    color: common.NamedColor
    prefix: text.TextComponent
    suffix: text.TextComponent

class Scoreboard:
    
    def add_objective(self, name: str, display_name: text.TextComponent, render_type: RenderType) -> None:
        raise NotImplementedError
    def remove_objective(self, name: str) -> None:
        raise NotImplementedError
    def set_display_slot(self, slot: DisplaySlot, objective_name: str) -> None:
        raise NotImplementedError
    def update_score(self, entity_name: str, objective_name: str, value: int) -> None:
        raise NotImplementedError
    def remove_score(self, entity_name: str, objective_name: str) -> None:
        raise NotImplementedError
    def create_team(self, name: str, settings: TeamSettings) -> None:
        raise NotImplementedError
    def remove_team(self, name: str) -> None:
        raise NotImplementedError
    def update_team(self, name: str, settings: TeamSettings) -> None:
        raise NotImplementedError
    def add_player_to_team(self, team_name: str, player_name: str) -> None:
        raise NotImplementedError
    def remove_player_from_team(self, team_name: str, player_name: str) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



