# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import common
from ..imports import text
from ..imports import scoreboard

class PistonBehavior(Enum):
    """
    Defines how a block reacts when pushed by a piston.
    """
    NORMAL = 0
    DESTROY = 1
    BLOCK = 2
    IGNORE = 3
    PUSH_ONLY = 4

class SoundCategory(Enum):
    """
    Categories for sounds to control their volume independently.
    """
    MASTER = 0
    MUSIC = 1
    RECORDS = 2
    WEATHER = 3
    BLOCKS = 4
    HOSTILE = 5
    NEUTRAL = 6
    PLAYERS = 7
    AMBIENT = 8
    VOICE = 9

class ExplosionInteraction(Enum):
    """
    Defines how an explosion interacts with blocks in the world.
    """
    NONE = 0
    BLOCK = 1
    MOB = 2
    TNT = 3
    TRIGGER = 4

class BlockFlags(Flag):
    """
    Flags used to control block updates and notifications.
    """
    NOTIFY_NEIGHBORS = auto()
    NOTIFY_LISTENERS = auto()
    FORCE_STATE = auto()
    SKIP_DROPS = auto()
    MOVED = auto()
    SKIP_REDSTONE_WIRE_STATE_REPLACEMENT = auto()
    SKIP_BLOCK_ENTITY_REPLACED_CALLBACK = auto()
    SKIP_BLOCK_ADDED_CALLBACK = auto()

@dataclass
class BlockState:
    """
    Detailed information about a block's state.
    """
    id: int
    luminance: int
    opacity: int
    hardness: float
    is_air: bool
    is_liquid: bool
    is_solid: bool
    is_full_cube: bool
    piston_behavior: PistonBehavior
    has_random_ticks: bool

@dataclass
class BlockStateId:
    """
    A simple wrapper for a block state ID.
    """
    id: int

@dataclass
class BlockPos:
    """
    A position in the world grid.
    """
    x: int
    y: int
    z: int

class World:
    """
    Represents a Minecraft world (dimension).
    """
    
    def get_id(self) -> str:
        """
        Returns the unique identifier of this world.
        """
        raise NotImplementedError
    def get_block_state_id(self, pos: BlockPos) -> int:
        """
        Gets the block state ID at the specified position.
        """
        raise NotImplementedError
    def get_block_state(self, pos: BlockPos) -> BlockState:
        """
        Gets detailed block state information at the specified position.
        """
        raise NotImplementedError
    def set_block_state(self, pos: BlockPos, state: int, update_flags: BlockFlags) -> None:
        """
        Sets the block state at the specified position.
        """
        raise NotImplementedError
    def get_time_of_day(self) -> int:
        """
        Returns the current time of day in ticks.
        """
        raise NotImplementedError
    def set_time_of_day(self, time: int) -> None:
        """
        Sets the current time of day in ticks.
        """
        raise NotImplementedError
    def get_world_age(self) -> int:
        """
        Returns the total age of the world in ticks.
        """
        raise NotImplementedError
    def get_dimension(self) -> str:
        """
        Returns the dimension type (e.g., "minecraft:overworld").
        """
        raise NotImplementedError
    def get_top_block_y(self, x: int, z: int) -> int:
        """
        Gets the highest non-air block Y coordinate at the specified X and Z.
        """
        raise NotImplementedError
    def get_motion_blocking_height(self, x: int, z: int) -> int:
        """
        Gets the highest motion-blocking block Y coordinate.
        """
        raise NotImplementedError
    def is_raining(self) -> bool:
        """
        Returns whether it is currently raining or snowing.
        """
        raise NotImplementedError
    def set_raining(self, raining: bool) -> None:
        """
        Sets whether it should be raining or snowing.
        """
        raise NotImplementedError
    def is_thundering(self) -> bool:
        """
        Returns whether there is currently a thunderstorm.
        """
        raise NotImplementedError
    def set_thundering(self, thundering: bool) -> None:
        """
        Sets whether there should be a thunderstorm.
        """
        raise NotImplementedError
    def broadcast_system_message(self, message: text.TextComponent, overlay: bool) -> None:
        """
        Broadcasts a system message to all players in this world.
        """
        raise NotImplementedError
    def get_scoreboard(self) -> scoreboard.Scoreboard:
        """
        Returns the scoreboard associated with this world.
        """
        raise NotImplementedError
    def play_sound(self, sound: str, category: SoundCategory, pos: Tuple[float, float, float], volume: float, pitch: float) -> None:
        """
        Plays a sound at the specified position for all players in the world.
        """
        raise NotImplementedError
    def spawn_particle(self, particle: str, pos: Tuple[float, float, float], offset: Tuple[float, float, float], max_speed: float, count: int) -> None:
        """
        Spawns particles at the specified position.
        """
        raise NotImplementedError
    def create_explosion(self, pos: Tuple[float, float, float], power: float, create_fire: bool, interaction: ExplosionInteraction) -> None:
        """
        Creates an explosion at the specified position.
        """
        raise NotImplementedError
    def get_sea_level(self) -> int:
        """
        Returns the sea level of this world.
        """
        raise NotImplementedError
    def get_min_y(self) -> int:
        """
        Returns the minimum Y coordinate (bottom of the world).
        """
        raise NotImplementedError
    def get_entities(self) -> List[Any]:
        """
        Returns a list of all entities in this world.
        """
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError


class Entity:
    
    def get_id(self) -> int:
        raise NotImplementedError
    def get_uuid(self) -> str:
        raise NotImplementedError
    def get_type(self) -> str:
        raise NotImplementedError
    def get_position(self) -> Tuple[float, float, float]:
        raise NotImplementedError
    def get_world(self) -> World:
        raise NotImplementedError
    def get_yaw(self) -> float:
        raise NotImplementedError
    def get_pitch(self) -> float:
        raise NotImplementedError
    def get_head_yaw(self) -> float:
        raise NotImplementedError
    def is_on_ground(self) -> bool:
        raise NotImplementedError
    def is_sneaking(self) -> bool:
        raise NotImplementedError
    def is_sprinting(self) -> bool:
        raise NotImplementedError
    def is_invisible(self) -> bool:
        raise NotImplementedError
    def is_glowing(self) -> bool:
        raise NotImplementedError
    def teleport(self, pos: Tuple[float, float, float], world_ref: World) -> None:
        raise NotImplementedError
    def set_velocity(self, velocity: Tuple[float, float, float]) -> None:
        raise NotImplementedError
    def get_velocity(self) -> Tuple[float, float, float]:
        raise NotImplementedError
    def get_pose(self) -> common.EntityPose:
        raise NotImplementedError
    def get_name(self) -> text.TextComponent:
        raise NotImplementedError
    def set_custom_name(self, name: text.TextComponent) -> None:
        raise NotImplementedError
    def get_custom_name(self) -> Optional[text.TextComponent]:
        raise NotImplementedError
    def set_custom_name_visible(self, visible: bool) -> None:
        raise NotImplementedError
    def is_custom_name_visible(self) -> bool:
        raise NotImplementedError
    def is_invulnerable(self) -> bool:
        raise NotImplementedError
    def set_invulnerable(self, invulnerable: bool) -> None:
        raise NotImplementedError
    def get_fire_ticks(self) -> int:
        raise NotImplementedError
    def set_fire_ticks(self, ticks: int) -> None:
        raise NotImplementedError
    def remove(self) -> None:
        raise NotImplementedError
    def __enter__(self) -> Self:
        """Returns self"""
        return self
                                
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None) -> bool | None:
        """
        Release this resource.
        """
        raise NotImplementedError



